-- TABLA: CheckStatus (Estados de Cheques)
CREATE TABLE CheckStatus (
    StatusId INT IDENTITY(1,1) PRIMARY KEY,
    StatusName VARCHAR(25) NOT NULL UNIQUE,            -- 'EMITIDO', 'CIRCULACION', 'COBRADO', 'PAGADO', 'ANULADO'
    Description VARCHAR(255),
    IsActive BIT DEFAULT 1
);

SELECT * FROM CheckStatus

INSERT INTO CheckStatus(StatusName, Description, IsActive) VALUES

('EMITIDO','CHEQUE GENERADO EN SECRON, AÚN NO EN CIRCULACIÓN',1),
('CIRCULACIÓN','CHEQUE QUE YA SALIÓ DE OFICINAS CENTRALES, ESTA CIRCULANDO',1),
('COBRADO','CHEQUE QUE FUE COBRADO POR EL BENEFICIARIO',1),
('PAGADO','CHEQUE DEPOSITADO AL BENEFICIARIO',1),
('ANULADO','CHEQUE ANULADO POR INFORMACIÓN ERRONEA O PAGO CANCELADO',1);