-- TABLA: Permissions (Permisos del Sistema)
CREATE TABLE Permissions (
    PermissionId INT IDENTITY(1,1) PRIMARY KEY,
    PermissionCode VARCHAR(50) NOT NULL UNIQUE,
    PermissionName VARCHAR(100) NOT NULL,
    Description VARCHAR(255),
    ModuleName VARCHAR(50), -- Ej: 'Security', 'Accounting', 'Reports'
    ActionType VARCHAR(20), -- 'Create', 'Read', 'Update', 'Delete', 'Execute'
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME DEFAULT GETDATE()
);

SELECT * FROM Permissions

--MODULOS DISPONIBLES
--COLABORADORES (Employees)
--USUARIOS (Users)
--PROVEEDORES (Suppliers)
--CUENTAS (Accounts)
--COMPRAS (Orders)
--KARDEX
--GASTOS (Bills)
--CHEQUES (Checks)
--BANCOS (Banks)
--LIBROS CONTABLES (Accounting Books)
--SEDES (Locations)
----ACTIVOS FIJOS (Static Items)

--// Formato: MODULO_ACCION
--"USUARIOS_CREAR"
--"USUARIOS_VER"
--"USUARIOS_EDITAR"
--"USUARIOS_ELIMINAR"
--"ROLES_ASIGNAR"
--"PERMISOS_GESTIONAR"
--"COMPRAS_APROBAR"
--"REPORTES_GENERAR"
--"SISTEMA_CONFIGURAR"

--// Formato: MOD_XXX (3 letras módulo + número)
--"USR_001"  // Crear usuarios
--"USR_002"  // Ver usuarios
--"USR_003"  // Editar usuarios
--"ROL_001"  // Asignar roles
--"PER_001"  // Gestionar permisos
--"COM_001"  // Crear compras
--"REP_001"  // Generar reportes

--"CREATE"    // Crear
--"READ"      // Leer/Ver
--"UPDATE"    // Actualizar/Editar
--"INACTIVE"    // Desactivar
--"APPROVE"   // Aprobar
--"EXPORT"    // Exportar
--"IMPORT"    // Importar
--"EXECUTE"   // Ejecutar
--"TAB"		  // Pestaña Visible


INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
VALUES 
-- ==================================================== EMPLOYEES ============================================================================

-- EMPLEADOS MENU PRINCIPAL
('EMP_001', 'EMPLOYEES_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA GESTIÓN DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

-- EMPLEADOS MODULO GESTIÓN DE EMPLEADOS
('EMP_002', 'EMPLOYEES_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_003', 'EMPLOYEES_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_004', 'EMPLOYEES_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE LOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_005', 'EMPLOYEES_MANAGMENT_UPDATE', 'PERMITE MODIFICAR INFORMACIÓN DE LOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_006', 'EMPLOYEES_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_007', 'EMPLOYEES_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_008', 'EMPLOYEES_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO INFORMACIÓN LABORAL
('EMP_009', 'EMPLOYEES_INFORMATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_010', 'EMPLOYEES_INFORMATION_CREATE', 'PERMITE REGISTRAR NUEVA INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_011', 'EMPLOYEES_INFORMATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_012', 'EMPLOYEES_INFORMATION_UPDATE', 'PERMITE MODIFICAR INFORMACIÓN DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_013', 'EMPLOYEES_INFORMATION_INACTIVE', 'PERMITE DESACTIVAR INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_014', 'EMPLOYEES_INFORMATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_015', 'EMPLOYEES_INFORMATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO CONFIGURACIÓN SALARIAL
('EMP_016', 'EMPLOYEES_SALARY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_017', 'EMPLOYEES_SALARY_CREATE', 'PERMITE REGISTRAR NUEVA CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_018', 'EMPLOYEES_SALARY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_019', 'EMPLOYEES_SALARY_UPDATE', 'PERMITE MODIFICAR CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_020', 'EMPLOYEES_SALARY_INACTIVE', 'PERMITE DESACTIVAR CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_021', 'EMPLOYEES_SALARY_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_022', 'EMPLOYEES_SALARY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO NOMINA
('EMP_023', 'EMPLOYEES_NOMINA', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_024', 'EMPLOYEES_NOMINA_CREATE', 'PERMITE REGISTRAR NUEVA NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_025', 'EMPLOYEES_NOMINA_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_026', 'EMPLOYEES_NOMINA_UPDATE', 'PERMITE MODIFICAR NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_027', 'EMPLOYEES_NOMINA_INACTIVE', 'PERMITE DESACTIVAR NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_028', 'EMPLOYEES_NOMINA_EXPORT', 'PERMITE EXPORTAR LISTADO DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_029', 'EMPLOYEES_NOMINA_IMPORT', 'PERMITE IMPORTAR LISTADOS DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO DEPARTMENTS
('EMP_030', 'EMPLOYEES_DEPARTMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_031', 'EMPLOYEES_DEPARTMENTS_CREATE', 'PERMITE REGISTRAR NUEVA DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_032', 'EMPLOYEES_DEPARTMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_033', 'EMPLOYEES_DEPARTMENTS_UPDATE', 'PERMITE MODIFICAR DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_034', 'EMPLOYEES_DEPARTMENTS_INACTIVE', 'PERMITE DESACTIVAR DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_035', 'EMPLOYEES_DEPARTMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_036', 'EMPLOYEES_DEPARTMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO TEACHERS
('EMP_037', 'EMPLOYEES_TEACHERS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_038', 'EMPLOYEES_TEACHERS_CREATE', 'PERMITE REGISTRAR NUEVA DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_039', 'EMPLOYEES_TEACHERS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_040', 'EMPLOYEES_TEACHERS_UPDATE', 'PERMITE MODIFICAR DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_041', 'EMPLOYEES_TEACHERS_INACTIVE', 'PERMITE DESACTIVAR DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_042', 'EMPLOYEES_TEACHERS_EXPORT', 'PERMITE EXPORTAR LISTADO DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_043', 'EMPLOYEES_TEACHERS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO HISTORIAL Y AUDITORÍA
('EMP_044', 'EMPLOYEES_HISTORY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_045', 'EMPLOYEES_HISTORY_CREATE', 'PERMITE REGISTRAR NUEVA HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_046', 'EMPLOYEES_HISTORY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_047', 'EMPLOYEES_HISTORY_UPDATE', 'PERMITE MODIFICAR HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_048', 'EMPLOYEES_HISTORY_INACTIVE', 'PERMITE DESACTIVAR HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_049', 'EMPLOYEES_HISTORY_EXPORT', 'PERMITE EXPORTAR LISTADO DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_050', 'EMPLOYEES_HISTORY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- ==================================================== USERS ============================================================================

-- USERS MENU PRINCIPAL
('USR_001', 'USERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

-- USERS MODULO MANAGMENT USERS
('USR_002', 'USERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_003', 'USERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_004', 'USERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_005', 'USERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_006', 'USERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_007', 'USERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_008', 'USERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO ROLES Y PERMISOS
('USR_009', 'USERS_ROLEPERMISSIONS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_010', 'USERS_ROLEPERMISSIONS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_011', 'USERS_ROLEPERMISSIONS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_012', 'USERS_ROLEPERMISSIONS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_013', 'USERS_ROLEPERMISSIONS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_014', 'USERS_ROLEPERMISSIONS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_015', 'USERS_ROLEPERMISSIONS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO SEGURIDAD Y ACCESOS
('USR_016', 'USERS_SECURITYACCESS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_017', 'USERS_SECURITYACCESS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_018', 'USERS_SECURITYACCESS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_019', 'USERS_SECURITYACCESS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_020', 'USERS_SECURITYACCESS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_021', 'USERS_SECURITYACCESS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_022', 'USERS_SECURITYACCESS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO ADMINISTRADOR CONFIGURACIÓN DE USUARIOS
('USR_023', 'USERS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_024', 'USERS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_025', 'USERS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_026', 'USERS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_027', 'USERS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_028', 'USERS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_029', 'USERS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- ==================================================== SUPPLIERS ============================================================================

-- SUPPLIERS MENU PRINCIPAL
('SUP_001', 'SUPPLIERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA SUPPLIERS EN EL SISTEMA.', 'SUPPLIERS', 'TAB'),

-- SUPPLIERS MODULO MANAGMENT SUPPLIERS
('SUP_002', 'SUPPLIERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'TAB'),

('SUP_003', 'SUPPLIERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'CREATE'),

('SUP_004', 'SUPPLIERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'READ'),

('SUP_005', 'SUPPLIERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'UPDATE'),

('SUP_006', 'SUPPLIERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'INACTIVE'),

('SUP_007', 'SUPPLIERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'EXPORT'),

('SUP_008', 'SUPPLIERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'IMPORT'),

-- ==================================================== ACCOUNTS ============================================================================
('ACC_001', 'ACCOUNTS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA ACCOUNTS EN EL SISTEMA.', 'ACCOUNTS', 'TAB'),

-- ACCOUNTS MODULO MANAGMENT ACCOUNTS
('ACC_002', 'ACCOUNTS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'TAB'),

('ACC_003', 'ACCOUNTS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'CREATE'),

('ACC_004', 'ACCOUNTS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'READ'),

('ACC_005', 'ACCOUNTS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'UPDATE'),

('ACC_006', 'ACCOUNTS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'INACTIVE'),

('ACC_007', 'ACCOUNTS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'EXPORT'),

('ACC_008', 'ACCOUNTS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'IMPORT'),

-- ==================================================== PURCHASEORDERS ============================================================================
('PUR_001', 'PURCHASEORDERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA PURCHASEORDERS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

-- PURCHASEORDERS MODULO REQUEST PURCHASEORDERS
('PUR_002', 'PURCHASEORDERS_REQUEST', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_003', 'PURCHASEORDERS_REQUEST_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_004', 'PURCHASEORDERS_REQUEST_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_005', 'PURCHASEORDERS_REQUEST_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_006', 'PURCHASEORDERS_REQUEST_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_007', 'PURCHASEORDERS_REQUEST_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_008', 'PURCHASEORDERS_REQUEST_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT'),

-- PURCHASEORDERS MODULO REQUISITION PURCHASEORDERS

('PUR_009', 'PURCHASEORDERS_REQUISITION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_010', 'PURCHASEORDERS_REQUISITION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_011', 'PURCHASEORDERS_REQUISITION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_012', 'PURCHASEORDERS_REQUISITION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_013', 'PURCHASEORDERS_REQUISITION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_014', 'PURCHASEORDERS_REQUISITION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_015', 'PURCHASEORDERS_REQUISITION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT'),

-- PURCHASEORDERS MODULO MANAGMENT PURCHASEORDERS

('PUR_016', 'PURCHASEORDERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_017', 'PURCHASEORDERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_018', 'PURCHASEORDERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_019', 'PURCHASEORDERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_020', 'PURCHASEORDERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_021', 'PURCHASEORDERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_022', 'PURCHASEORDERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT'),

-- ==================================================== INVENTORY ============================================================================
('KDX_001', 'KARDEX_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA KARDEX EN EL SISTEMA.', 'KARDEX', 'TAB'),

-- KARDEX MODULO CATALOG ITEMS KARDEX
('KDX_002', 'KARDEX_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_003', 'KARDEX_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_004', 'KARDEX_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_005', 'KARDEX_CATALOG_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_006', 'KARDEX_CATALOG_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_007', 'KARDEX_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_008', 'KARDEX_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DE ITEMS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO INVENTARIO 

('KDX_009', 'KARDEX_INVENTORY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_010', 'KARDEX_INVENTORY_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_011', 'KARDEX_INVENTORY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_012', 'KARDEX_INVENTORY_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_013', 'KARDEX_INVENTORY_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_014', 'KARDEX_INVENTORY_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_015', 'KARDEX_INVENTORY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE INVENTARIOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO COST VALUATION 

('KDX_016', 'KARDEX_COSTVALUATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_017', 'KARDEX_COSTVALUATION_CREATE', 'PERMITE REGISTRAR NUEVA VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_018', 'KARDEX_COSTVALUATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_019', 'KARDEX_COSTVALUATION_UPDATE', 'PERMITE MODIFICAR VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_020', 'KARDEX_COSTVALUATION_INACTIVE', 'PERMITE DESACTIVAR VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_021', 'KARDEX_COSTVALUATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_022', 'KARDEX_COSTVALUATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE VALORIZACIÓN DE COSTOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO INPUT CONTROL

('KDX_023', 'KARDEX_INPUTCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_024', 'KARDEX_INPUTCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_025', 'KARDEX_INPUTCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_026', 'KARDEX_INPUTCONTROL_UPDATE', 'PERMITE MODIFICAR CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_027', 'KARDEX_INPUTCONTROL_INACTIVE', 'PERMITE DESACTIVAR CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_028', 'KARDEX_INPUTCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_029', 'KARDEX_INPUTCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONTROL DE INSUMOS EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- KARDEX MODULO REPORTS

('KDX_030', 'KARDEX_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'TAB'),

('KDX_031', 'KARDEX_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_032', 'KARDEX_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_033', 'KARDEX_REPORTS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_034', 'KARDEX_REPORTS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_035', 'KARDEX_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_036', 'KARDEX_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'IMPORT'),

-- ==================================================== BILLS ============================================================================
('BIL_001', 'BILLS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA BILLS EN EL SISTEMA.', 'BILLS', 'TAB'),

-- BILLS MENU MANAGMENT
('BIL_002', 'BILLS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_003', 'BILLS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_004', 'BILLS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_005', 'BILLS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_006', 'BILLS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_007', 'BILLS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_008', 'BILLS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU CATEGORIES
('BIL_009', 'BILLS_CATEGORIES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_010', 'BILLS_CATEGORIES_CREATE', 'PERMITE REGISTRAR NUEVA CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_011', 'BILLS_CATEGORIES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_012', 'BILLS_CATEGORIES_UPDATE', 'PERMITE MODIFICAR CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_013', 'BILLS_CATEGORIES_INACTIVE', 'PERMITE DESACTIVAR CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_014', 'BILLS_CATEGORIES_EXPORT', 'PERMITE EXPORTAR LISTADO DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_015', 'BILLS_CATEGORIES_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU AUTHORIZATION
('BIL_016', 'BILLS_AUTHORIZATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_017', 'BILLS_AUTHORIZATION_CREATE', 'PERMITE REGISTRAR NUEVA AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_018', 'BILLS_AUTHORIZATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_019', 'BILLS_AUTHORIZATION_UPDATE', 'PERMITE MODIFICAR AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_020', 'BILLS_AUTHORIZATION_INACTIVE', 'PERMITE DESACTIVAR AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_021', 'BILLS_AUTHORIZATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_022', 'BILLS_AUTHORIZATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU BUDGET CONTROL
('BIL_023', 'BILLS_BUDGETCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_024', 'BILLS_BUDGETCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_025', 'BILLS_BUDGETCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_026', 'BILLS_BUDGETCONTROL_UPDATE', 'PERMITE MODIFICAR CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_027', 'BILLS_BUDGETCONTROL_INACTIVE', 'PERMITE DESACTIVAR CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_028', 'BILLS_BUDGETCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_029', 'BILLS_BUDGETCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU REPORTS
('BIL_030', 'BILLS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA REPORTERÍA EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_031', 'BILLS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_032', 'BILLS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_033', 'BILLS_REPORTS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_034', 'BILLS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_035', 'BILLS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_036', 'BILLS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU REPORTS
('BIL_037', 'BILLS_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_038', 'BILLS_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_039', 'BILLS_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_040', 'BILLS_CATALOG_UPDATE', 'PERMITE MODIFICAR CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_041', 'BILLS_CATALOG_INACTIVE', 'PERMITE DESACTIVAR CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_042', 'BILLS_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_043', 'BILLS_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- ==================================================== CHECKS ============================================================================
('CHK_001', 'CHECKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA CHECKS EN EL SISTEMA.', 'CHECKS', 'TAB'),

-- CHECKS MENU MANAGMENT
('CHK_002', 'CHECKS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_003', 'CHECKS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_004', 'CHECKS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_005', 'CHECKS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_006', 'CHECKS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_007', 'CHECKS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_008', 'CHECKS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS MENU CHECKBOOKS
('CHK_009', 'CHECKS_CHECKBOOKS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_010', 'CHECKS_CHECKBOOKS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_011', 'CHECKS_CHECKBOOKS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_012', 'CHECKS_CHECKBOOKS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_013', 'CHECKS_CHECKBOOKS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_014', 'CHECKS_CHECKBOOKS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_015', 'CHECKS_CHECKBOOKS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS MENU REPORTS
('CHK_016', 'CHECKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_017', 'CHECKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_018', 'CHECKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_019', 'CHECKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_020', 'CHECKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_021', 'CHECKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_022', 'CHECKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),


-- CHECKS MENU CONFIGURATION
('CHK_023', 'CHECKS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_024', 'CHECKS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_025', 'CHECKS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_026', 'CHECKS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_027', 'CHECKS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_028', 'CHECKS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_029', 'CHECKS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS PREDECLARACIÓN, ASIGNACIÓN DE RANGOS DE CHEQUES, ACTUALIZAR NUMERACIÓN DE CHEQUES

('CHK_030', 'CHECKS_REPORTS_UPDATENUMBER', 'PERMITE ACTUALIZAR LA NUMERACIÓN DEL CHEQUE', 'CHECKS', 'UPDATE'),

('CHK_031', 'CHECKS_REPORTS_CREATEPREDECLARATION', 'PERMITE GENERAR EL PROCESO DE PREDECLARACIÓN DE CHEQUESE EN EL SISTEMA', 'CHECKS', 'CREATE'),

('CHK_032', 'CHECKS_MANAGMENT_ASSIGNMENT', 'PERMITE ASIGNACIÓN DE CHEQUES EN EL SISTEMA', 'CHECKS', 'CREATE'),

('CHK_033', 'CHECKS_REPORTS_BASEFLUJO', 'PERMITE GENERAR EL REPORTE DE BASE DE FLUJO DE CHEQUES EN EL SISTEMA', 'CHECKS', 'EXPORT'),

-- CHECKS MENU FILECONTROL
('CHK_034', 'CHECKS_FILECONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_035', 'CHECKS_FILECONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_036', 'CHECKS_FILECONTROL_PROCESOTOTAL', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A CUALQUIER ESTADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_037', 'CHECKS_FILECONTROL_PROCESOPENDIENTE', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A PENDIENTE GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_038', 'CHECKS_FILECONTROL_PROCESOTRASLADADO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A TRASLADADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_039', 'CHECKS_FILECONTROL_PROCESORECIBIDO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A RECIBIDO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_040', 'CHECKS_FILECONTROL_PROCESOARCHIVADO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A ARCHIVADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

-- ==================================================== BANKS ============================================================================
('BNK_001', 'BANKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA BANKS EN EL SISTEMA.', 'BANKS', 'TAB'),

-- BANKS MENU ACCOUNTS
('BNK_002', 'BANKS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_003', 'BANKS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_004', 'BANKS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_005', 'BANKS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_006', 'BANKS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_007', 'BANKS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_008', 'BANKS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU MOVEMENTS
('BNK_009', 'BANKS_MOVEMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_010', 'BANKS_MOVEMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_011', 'BANKS_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_012', 'BANKS_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_013', 'BANKS_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_014', 'BANKS_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_015', 'BANKS_MOVEMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CONCILIATION
('BNK_016', 'BANKS_CONCILIATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_017', 'BANKS_CONCILIATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_018', 'BANKS_CONCILIATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_019', 'BANKS_CONCILIATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_020', 'BANKS_CONCILIATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_021', 'BANKS_CONCILIATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_022', 'BANKS_CONCILIATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CASHCONTROL
('BNK_023', 'BANKS_CASHCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_024', 'BANKS_CASHCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_025', 'BANKS_CASHCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_026', 'BANKS_CASHCONTROL_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_027', 'BANKS_CASHCONTROL_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_028', 'BANKS_CASHCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_029', 'BANKS_CASHCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU REPORTS
('BNK_030', 'BANKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_031', 'BANKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_032', 'BANKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_033', 'BANKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_034', 'BANKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_035', 'BANKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_036', 'BANKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CONFIGURATION
('BNK_037', 'BANKS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_038', 'BANKS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_039', 'BANKS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_040', 'BANKS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_041', 'BANKS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_042', 'BANKS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_043', 'BANKS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- ==================================================== ACCOUNTING BOOKS ============================================================================
('ACB_001', 'ACCOUNTINGBOOKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA ACCOUNTINGBOOKS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

-- ACCOUNTING BOOKS MENU DAILYBOOK
('ACB_002', 'ACCOUNTINGBOOKS_DAILYBOOK', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_003', 'ACCOUNTINGBOOKS_DAILYBOOK_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_004', 'ACCOUNTINGBOOKS_DAILYBOOK_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_005', 'ACCOUNTINGBOOKS_DAILYBOOK_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_006', 'ACCOUNTINGBOOKS_DAILYBOOK_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_007', 'ACCOUNTINGBOOKS_DAILYBOOK_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_008', 'ACCOUNTINGBOOKS_DAILYBOOK_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU LEDGER (LIBRO MAYOR)
('ACB_009', 'ACCOUNTINGBOOKS_LEDGER', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_010', 'ACCOUNTINGBOOKS_LEDGER_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_011', 'ACCOUNTINGBOOKS_LEDGER_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_012', 'ACCOUNTINGBOOKS_LEDGER_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_013', 'ACCOUNTINGBOOKS_LEDGER_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_014', 'ACCOUNTINGBOOKS_LEDGER_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_015', 'ACCOUNTINGBOOKS_LEDGER_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU FINANCIAL STATEMANTS
('ACB_016', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_017', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_018', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_019', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_020', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_021', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_022', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU CLOSING
('ACB_023', 'ACCOUNTINGBOOKS_CLOSING', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_024', 'ACCOUNTINGBOOKS_CLOSING_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_025', 'ACCOUNTINGBOOKS_CLOSING_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_026', 'ACCOUNTINGBOOKS_CLOSING_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_027', 'ACCOUNTINGBOOKS_CLOSING_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_028', 'ACCOUNTINGBOOKS_CLOSING_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_029', 'ACCOUNTINGBOOKS_CLOSING_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU REPORTS
('ACB_030', 'ACCOUNTINGBOOKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_031', 'ACCOUNTINGBOOKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_032', 'ACCOUNTINGBOOKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_033', 'ACCOUNTINGBOOKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_034', 'ACCOUNTINGBOOKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_035', 'ACCOUNTINGBOOKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_036', 'ACCOUNTINGBOOKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU CATALOG
('ACB_037', 'ACCOUNTINGBOOKS_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_038', 'ACCOUNTINGBOOKS_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_039', 'ACCOUNTINGBOOKS_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_040', 'ACCOUNTINGBOOKS_CATALOG_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_041', 'ACCOUNTINGBOOKS_CATALOG_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_042', 'ACCOUNTINGBOOKS_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_043', 'ACCOUNTINGBOOKS_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ==================================================== LOCATIONS ============================================================================
('LOC_001', 'LOCATIONS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA LOCATIONS EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

-- LOCATIONS MENU MANAGMENT
('LOC_002', 'LOCATIONS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_003', 'LOCATIONS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_004', 'LOCATIONS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_005', 'LOCATIONS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_006', 'LOCATIONS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_007', 'LOCATIONS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_008', 'LOCATIONS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU CONFIGURATION
('LOC_009', 'LOCATIONS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_010', 'LOCATIONS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_011', 'LOCATIONS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_012', 'LOCATIONS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_013', 'LOCATIONS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_014', 'LOCATIONS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_015', 'LOCATIONS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU FINANTIAL CONTROL
('LOC_016', 'LOCATIONS_FINANTIALCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_017', 'LOCATIONS_FINANTIALCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_018', 'LOCATIONS_FINANTIALCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_019', 'LOCATIONS_FINANTIALCONTROL_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_020', 'LOCATIONS_FINANTIALCONTROL_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_021', 'LOCATIONS_FINANTIALCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_022', 'LOCATIONS_FINANTIALCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU DEPARTMENTS
('LOC_023', 'LOCATIONS_DEPARTMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_024', 'LOCATIONS_DEPARTMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_025', 'LOCATIONS_DEPARTMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_026', 'LOCATIONS_DEPARTMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_027', 'LOCATIONS_DEPARTMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_028', 'LOCATIONS_DEPARTMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_029', 'LOCATIONS_DEPARTMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU STAFF
('LOC_030', 'LOCATIONS_STAFF', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_031', 'LOCATIONS_STAFF_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_032', 'LOCATIONS_STAFF_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_033', 'LOCATIONS_STAFF_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_034', 'LOCATIONS_STAFF_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_035', 'LOCATIONS_STAFF_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_036', 'LOCATIONS_STAFF_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- ==================================================== STATIC ITEMS ============================================================================
('STC_001', 'STATICITEMS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA STATICITEMS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

-- STATIC ITEMS MENU MANAGMENT
('STC_002', 'STATICITEMS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_003', 'STATICITEMS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_004', 'STATICITEMS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_005', 'STATICITEMS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_006', 'STATICITEMS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_007', 'STATICITEMS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_008', 'STATICITEMS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU RESPONSLETTER (RESPONSABILITY LETTER)
('STC_009', 'STATICITEMS_RESPONSLETTER', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_010', 'STATICITEMS_RESPONSLETTER_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_011', 'STATICITEMS_RESPONSLETTER_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_012', 'STATICITEMS_RESPONSLETTER_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_013', 'STATICITEMS_RESPONSLETTER_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_014', 'STATICITEMS_RESPONSLETTER_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_015', 'STATICITEMS_RESPONSLETTER_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CARTA DE RESPONSABILIDAD DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU MOVEMENTS
('STC_016', 'STATICITEMS_MOVEMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_017', 'STATICITEMS_MOVEMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_018', 'STATICITEMS_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_019', 'STATICITEMS_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_020', 'STATICITEMS_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_021', 'STATICITEMS_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_022', 'STATICITEMS_MOVEMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL DE MOVIMIENTOS DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU MAINTENANCE
('STC_023', 'STATICITEMS_MAINTENANCE', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_024', 'STATICITEMS_MAINTENANCE_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_025', 'STATICITEMS_MAINTENANCE_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_026', 'STATICITEMS_MAINTENANCE_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_027', 'STATICITEMS_MAINTENANCE_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_028', 'STATICITEMS_MAINTENANCE_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_029', 'STATICITEMS_MAINTENANCE_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE MANTENIMIENTO Y SOPORTE DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU DEPRECIATION Y VALUATION
('STC_030', 'STATICITEMS_DEPRECIATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_031', 'STATICITEMS_DEPRECIATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_032', 'STATICITEMS_DEPRECIATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_033', 'STATICITEMS_DEPRECIATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_034', 'STATICITEMS_DEPRECIATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_035', 'STATICITEMS_DEPRECIATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_036', 'STATICITEMS_DEPRECIATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DEPRECIACIÓN Y VALUACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU REPORTS
('STC_037', 'STATICITEMS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_038', 'STATICITEMS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_039', 'STATICITEMS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_040', 'STATICITEMS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_041', 'STATICITEMS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_042', 'STATICITEMS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_043', 'STATICITEMS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- STATIC ITEMS MENU CONFIGURATION
('STC_044', 'STATICITEMS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'TAB'),

('STC_045', 'STATICITEMS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'CREATE'),

('STC_046', 'STATICITEMS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'READ'),

('STC_047', 'STATICITEMS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'UPDATE'),

('STC_048', 'STATICITEMS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'INACTIVE'),

('STC_049', 'STATICITEMS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'EXPORT'),

('STC_050', 'STATICITEMS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE ACTIVOS FIJOS EN EL SISTEMA.', 'STATICITEMS', 'IMPORT'),

-- ==================================================== KARDEX ============================================================================

--KARDEX MODULO CATALOG LOCATIONS CATEGORIES
('KDX_037', 'KARDEX_CATLOCATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'KARDEX', 'TAB'),

('KDX_038', 'KARDEX_CATLOCATION_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'CREATE'),

('KDX_039', 'KARDEX_CATLOCATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'READ'),

('KDX_040', 'KARDEX_CATLOCATION_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'UPDATE'),

('KDX_041', 'KARDEX_CATLOCATION_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'INACTIVE'),

('KDX_042', 'KARDEX_CATLOCATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'EXPORT'),

('KDX_043', 'KARDEX_CATLOCATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'KARDEX', 'IMPORT'),


-- ==================================================== FIXED ASSETS ============================================================================

--FIXEDASSETS MODULO DE ACTIVOS FIJOS
('FA_001', 'FA_CATEGORIES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_002', 'FA_CATEGORIES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_003', 'FA_CATEGORIES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_004', 'FA_CATEGORIES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_005', 'FA_CATEGORIES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_006', 'FA_CATEGORIES_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_007', 'FA_ATTRIBUTES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_008', 'FA_ATTRIBUTES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_009', 'FA_ATTRIBUTES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),


-- ==================================================== TEACHERS ============================================================================
('TCH_001', 'TEACHERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

-- TEACHERS MENU TEACHERS_PERSONAL
('TCH_002', 'TEACHERS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONFIGURACIÓN ACADÉMICA EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_003', 'TEACHERS_PERSONAL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DOCENTES, COORDINADORES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_004', 'TEACHERS_SECTIONS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SECCIONES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_005', 'TEACHERS_SCHEDULES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE HORARIOS EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_006', 'TEACHERS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_007', 'TEACHERS_PERSONAL_TEACHERMANAGMENT', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_008', 'TEACHERS_PERSONAL_COORDINATORMANAGMENT', 'PERMITE REGISTRAR NUEVA GESTIÓN DE COORDINADORES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_009', 'TEACHERS_PERSONAL_ASSIGNMENTCOURSES', 'PERMITE REGISTRAR ASIGNACIÓN DE CURSOS DE DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),
-- ==================================================== FINANCES ============================================================================
('FNS_001', 'FINANCES_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA FINANZAS EN EL SISTEMA.', 'FINANCES', 'TAB'),

-- ==================================================== TRANSFERS ============================================================================
('TNS_001', 'TRANSFERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

-- TRANSFERS MENU TRANSFERS_MANAGMENT
('TNS_002', 'TRANSFERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

('TNS_003', 'TRANSFERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'CREATE'),

('TNS_004', 'TRANSFERS_MANAGMENT__READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'READ'),

('TNS_005', 'TRANSFERS_MANAGMENT__UPDATE', 'PERMITE MODIFICAR GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'UPDATE'),

('TNS_006', 'TRANSFERS_MANAGMENT__INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'INACTIVE'),

('TNS_007', 'TRANSFERS_MANAGMENT__EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'EXPORT'),

('TNS_008', 'TRANSFERS_MANAGMENT__IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'IMPORT'),

-- TRANSFERS MENU TRANSFERS_MANAGMENT
('TNS_009', 'TRANSFERS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

('TNS_010', 'TRANSFERS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'CREATE'),

('TNS_011', 'TRANSFERS_REPORTS__READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'READ'),

('TNS_012', 'TRANSFERS_REPORTS__UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'UPDATE'),

('TNS_013', 'TRANSFERS_REPORTS__INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'INACTIVE'),

('TNS_014', 'TRANSFERS_REPORTS__EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTES DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'EXPORT'),

('TNS_015', 'TRANSFERS_REPORTS__IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'IMPORT');

-- ****************************************************************************************************************************************************************************
-- ****************************************************************************************************************************************************************************

