-- TABLA: CheckStatus (Estados de Cheques)
CREATE TABLE TransferStatus (
    StatusId INT IDENTITY(1,1) PRIMARY KEY,
    StatusName VARCHAR(25) NOT NULL UNIQUE,            -- 'EN PROCESO', 'EXITOSA', 'CANCELADA', 'RECHAZADA'
    Description VARCHAR(255),
    IsActive BIT DEFAULT 1
);

SELECT * FROM TransferStatus

INSERT INTO TransferStatus(StatusName, Description, IsActive) VALUES

('EN PROCESO','TRANSFERENCIA QUE SE ENCUENTRA EN PROCESO DE SER GENERADA',1),
('COMPLETADA','TRANSFERENCIA COMPLETADA EXITOSAMENTE',1),
('CANCELADA','TRANSFERENCIA CANCELADA, PORQUE EL USUARIO LA DETUVO',1),
('RECHAZADA','TRANSFERENCIA FALLIDA, POR DATOS, LÍMITES, VALIDACIONES, ETC.',1);