INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 
-- ==================================================== SUPPLIERS ============================================================================

-- SUPPLIERS MENU PRINCIPAL
('SUP_001', 'SUPPLIERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA SUPPLIERS EN EL SISTEMA.', 'SUPPLIERS', 'TAB'),

-- SUPPLIERS MODULO MANAGMENT SUPPLIERS
('SUP_002', 'SUPPLIERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'TAB'),

('SUP_003', 'SUPPLIERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'CREATE'),

('SUP_004', 'SUPPLIERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'READ'),

('SUP_005', 'SUPPLIERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'UPDATE'),

('SUP_006', 'SUPPLIERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'INACTIVE'),

('SUP_007', 'SUPPLIERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'EXPORT'),

('SUP_008', 'SUPPLIERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE PROVEEDORES EN EL SISTEMA.', 'SUPPLIERS', 'IMPORT'),

-- ==================================================== PURCHASEORDERS ============================================================================
('PUR_001', 'PURCHASEORDERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA PURCHASEORDERS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

-- PURCHASEORDERS MODULO REQUEST PURCHASEORDERS
('PUR_002', 'PURCHASEORDERS_REQUEST', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_003', 'PURCHASEORDERS_REQUEST_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_004', 'PURCHASEORDERS_REQUEST_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_005', 'PURCHASEORDERS_REQUEST_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_006', 'PURCHASEORDERS_REQUEST_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_007', 'PURCHASEORDERS_REQUEST_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_008', 'PURCHASEORDERS_REQUEST_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE SOLICITUD DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT'),

-- PURCHASEORDERS MODULO REQUISITION PURCHASEORDERS

('PUR_009', 'PURCHASEORDERS_REQUISITION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_010', 'PURCHASEORDERS_REQUISITION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_011', 'PURCHASEORDERS_REQUISITION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_012', 'PURCHASEORDERS_REQUISITION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_013', 'PURCHASEORDERS_REQUISITION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_014', 'PURCHASEORDERS_REQUISITION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_015', 'PURCHASEORDERS_REQUISITION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REQUISICIÓN DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT'),

-- PURCHASEORDERS MODULO MANAGMENT PURCHASEORDERS

('PUR_016', 'PURCHASEORDERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'TAB'),

('PUR_017', 'PURCHASEORDERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'CREATE'),

('PUR_018', 'PURCHASEORDERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'READ'),

('PUR_019', 'PURCHASEORDERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'UPDATE'),

('PUR_020', 'PURCHASEORDERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'INACTIVE'),

('PUR_021', 'PURCHASEORDERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'EXPORT'),

('PUR_022', 'PURCHASEORDERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ORDENES DE COMPRAS EN EL SISTEMA.', 'PURCHASEORDERS', 'IMPORT')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)