INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 

-- ==================================================== USERS ============================================================================

-- USERS MENU PRINCIPAL
('USR_001', 'USERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

-- USERS MODULO MANAGMENT USERS
('USR_002', 'USERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_003', 'USERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_004', 'USERS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_005', 'USERS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_006', 'USERS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_007', 'USERS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_008', 'USERS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO ROLES Y PERMISOS
('USR_009', 'USERS_ROLEPERMISSIONS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_010', 'USERS_ROLEPERMISSIONS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_011', 'USERS_ROLEPERMISSIONS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_012', 'USERS_ROLEPERMISSIONS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_013', 'USERS_ROLEPERMISSIONS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_014', 'USERS_ROLEPERMISSIONS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_015', 'USERS_ROLEPERMISSIONS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ROLES Y PERMISOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO SEGURIDAD Y ACCESOS
('USR_016', 'USERS_SECURITYACCESS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_017', 'USERS_SECURITYACCESS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_018', 'USERS_SECURITYACCESS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_019', 'USERS_SECURITYACCESS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_020', 'USERS_SECURITYACCESS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_021', 'USERS_SECURITYACCESS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_022', 'USERS_SECURITYACCESS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE SEGURIDAD Y ACCESOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

-- USERS MODULO ADMINISTRADOR CONFIGURACIÓN DE USUARIOS
('USR_023', 'USERS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'TAB'),

('USR_024', 'USERS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'CREATE'),

('USR_025', 'USERS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'READ'),

('USR_026', 'USERS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'UPDATE'),

('USR_027', 'USERS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'INACTIVE'),

('USR_028', 'USERS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'EXPORT'),

('USR_029', 'USERS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE USUARIOS EN EL SISTEMA.', 'USERS', 'IMPORT'),

('ITSM_001', 'USERS_ITSM_TECHONOLOGY',        'PERMITE VISUALIZAR EL MÓDULO DE GESTIÓN DE EQUIPOS DE TECNOLOGÍA.', 'ITSM', 'TAB'),
('ITSM_002', 'ITSM_TECHNOLOGY_READ',           'PERMITE VISUALIZAR LA LISTA Y DETALLES DE EQUIPOS DE TECNOLOGÍA.',  'ITSM', 'READ'),
('ITSM_003', 'ITSM_TECHNOLOGY_UPDATE',         'PERMITE MODIFICAR EQUIPOS DE TECNOLOGÍA.',                          'ITSM', 'UPDATE'),
('ITSM_004', 'ITSM_TECHNOLOGY_EXPORT',         'PERMITE EXPORTAR LISTADO DE EQUIPOS DE TECNOLOGÍA.',                'ITSM', 'EXPORT'),
('ITSM_005', 'ITSM_TECHNOLOGY_PRINT_LETTER',   'PERMITE EMITIR CARTA DE RESPONSABILIDAD DE EQUIPOS.',              'ITSM', 'EXPORT'),
('ITSM_006', 'ITSM_CLASSIFICATION_TAB',        'PERMITE VISUALIZAR EL MÓDULO DE CLASIFICACIONES DE CATEGORÍAS.',   'ITSM', 'TAB'),
('ITSM_007', 'ITSM_CLASSIFICATION_CREATE',     'PERMITE REGISTRAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'CREATE'),
('ITSM_008', 'ITSM_CLASSIFICATION_UPDATE',     'PERMITE MODIFICAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'UPDATE'),
('ITSM_009', 'ITSM_CLASSIFICATION_INACTIVE',   'PERMITE INACTIVAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'INACTIVE')


) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)