CREATE OR ALTER PROCEDURE SP_AuditLog_DeleteOld
    @CutoffDate DATETIME
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;

    BEGIN TRANSACTION
    BEGIN TRY
        DELETE FROM AuditLog WHERE ActionDate < @CutoffDate;
        DECLARE @rows INT = @@ROWCOUNT;

        COMMIT TRANSACTION; SELECT @rows;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION; SELECT -1;
    END CATCH
END
GO