INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 
-- ==================================================== BILLS ============================================================================
('BIL_001', 'BILLS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA BILLS EN EL SISTEMA.', 'BILLS', 'TAB'),

-- BILLS MENU MANAGMENT
('BIL_002', 'BILLS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_003', 'BILLS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_004', 'BILLS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_005', 'BILLS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_006', 'BILLS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_007', 'BILLS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_008', 'BILLS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU CATEGORIES
('BIL_009', 'BILLS_CATEGORIES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_010', 'BILLS_CATEGORIES_CREATE', 'PERMITE REGISTRAR NUEVA CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_011', 'BILLS_CATEGORIES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_012', 'BILLS_CATEGORIES_UPDATE', 'PERMITE MODIFICAR CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_013', 'BILLS_CATEGORIES_INACTIVE', 'PERMITE DESACTIVAR CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_014', 'BILLS_CATEGORIES_EXPORT', 'PERMITE EXPORTAR LISTADO DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_015', 'BILLS_CATEGORIES_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CATEGORÍAS Y CONTABILIZACIÓN EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU AUTHORIZATION
('BIL_016', 'BILLS_AUTHORIZATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_017', 'BILLS_AUTHORIZATION_CREATE', 'PERMITE REGISTRAR NUEVA AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_018', 'BILLS_AUTHORIZATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_019', 'BILLS_AUTHORIZATION_UPDATE', 'PERMITE MODIFICAR AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_020', 'BILLS_AUTHORIZATION_INACTIVE', 'PERMITE DESACTIVAR AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_021', 'BILLS_AUTHORIZATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_022', 'BILLS_AUTHORIZATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE AUTORIZACIÓN DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU BUDGET CONTROL
('BIL_023', 'BILLS_BUDGETCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_024', 'BILLS_BUDGETCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_025', 'BILLS_BUDGETCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_026', 'BILLS_BUDGETCONTROL_UPDATE', 'PERMITE MODIFICAR CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_027', 'BILLS_BUDGETCONTROL_INACTIVE', 'PERMITE DESACTIVAR CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_028', 'BILLS_BUDGETCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_029', 'BILLS_BUDGETCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONTROL PRESUPUESTARIO EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU REPORTS
('BIL_030', 'BILLS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA REPORTERÍA EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_031', 'BILLS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_032', 'BILLS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_033', 'BILLS_REPORTS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_034', 'BILLS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_035', 'BILLS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_036', 'BILLS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE REPORTERÍA EN EL SISTEMA.', 'BILLS', 'IMPORT'),

-- BILLS MENU REPORTS
('BIL_037', 'BILLS_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'TAB'),

('BIL_038', 'BILLS_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'CREATE'),

('BIL_039', 'BILLS_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'READ'),

('BIL_040', 'BILLS_CATALOG_UPDATE', 'PERMITE MODIFICAR CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'UPDATE'),

('BIL_041', 'BILLS_CATALOG_INACTIVE', 'PERMITE DESACTIVAR CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'INACTIVE'),

('BIL_042', 'BILLS_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'EXPORT'),

('BIL_043', 'BILLS_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CALOTOGOS DE GASTOS EN EL SISTEMA.', 'BILLS', 'IMPORT')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)