INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 
-- ==================================================== ACCOUNTS ============================================================================
('ACC_001', 'ACCOUNTS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA ACCOUNTS EN EL SISTEMA.', 'ACCOUNTS', 'TAB'),

-- ACCOUNTS MODULO MANAGMENT ACCOUNTS
('ACC_002', 'ACCOUNTS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'TAB'),

('ACC_003', 'ACCOUNTS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'CREATE'),

('ACC_004', 'ACCOUNTS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'READ'),

('ACC_005', 'ACCOUNTS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'UPDATE'),

('ACC_006', 'ACCOUNTS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'INACTIVE'),

('ACC_007', 'ACCOUNTS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'EXPORT'),

('ACC_008', 'ACCOUNTS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CUENTAS CONTABLES EN EL SISTEMA.', 'ACCOUNTS', 'IMPORT'),
-- ==================================================== CHECKS ============================================================================
('CHK_001', 'CHECKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA CHECKS EN EL SISTEMA.', 'CHECKS', 'TAB'),

-- CHECKS MENU MANAGMENT
('CHK_002', 'CHECKS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_003', 'CHECKS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_004', 'CHECKS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_005', 'CHECKS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_006', 'CHECKS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_007', 'CHECKS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_008', 'CHECKS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS MENU CHECKBOOKS
('CHK_009', 'CHECKS_CHECKBOOKS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_010', 'CHECKS_CHECKBOOKS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_011', 'CHECKS_CHECKBOOKS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_012', 'CHECKS_CHECKBOOKS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_013', 'CHECKS_CHECKBOOKS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_014', 'CHECKS_CHECKBOOKS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_015', 'CHECKS_CHECKBOOKS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CHEQUERAS EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS MENU REPORTS
('CHK_016', 'CHECKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_017', 'CHECKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_018', 'CHECKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_019', 'CHECKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_020', 'CHECKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_021', 'CHECKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_022', 'CHECKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),


-- CHECKS MENU CONFIGURATION
('CHK_023', 'CHECKS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_024', 'CHECKS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'CREATE'),

('CHK_025', 'CHECKS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'READ'),

('CHK_026', 'CHECKS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_027', 'CHECKS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'INACTIVE'),

('CHK_028', 'CHECKS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_029', 'CHECKS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'IMPORT'),

-- CHECKS PREDECLARACIÓN, ASIGNACIÓN DE RANGOS DE CHEQUES, ACTUALIZAR NUMERACIÓN DE CHEQUES

('CHK_030', 'CHECKS_REPORTS_UPDATENUMBER', 'PERMITE ACTUALIZAR LA NUMERACIÓN DEL CHEQUE', 'CHECKS', 'UPDATE'),

('CHK_031', 'CHECKS_REPORTS_CREATEPREDECLARATION', 'PERMITE GENERAR EL PROCESO DE PREDECLARACIÓN DE CHEQUESE EN EL SISTEMA', 'CHECKS', 'CREATE'),

('CHK_032', 'CHECKS_MANAGMENT_ASSIGNMENT', 'PERMITE ASIGNACIÓN DE CHEQUES EN EL SISTEMA', 'CHECKS', 'CREATE'),

('CHK_033', 'CHECKS_REPORTS_BASEFLUJO', 'PERMITE GENERAR EL REPORTE DE BASE DE FLUJO DE CHEQUES EN EL SISTEMA', 'CHECKS', 'EXPORT'),

-- CHECKS MENU FILECONTROL
('CHK_034', 'CHECKS_FILECONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'TAB'),

('CHK_035', 'CHECKS_FILECONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'EXPORT'),

('CHK_036', 'CHECKS_FILECONTROL_PROCESOTOTAL', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A CUALQUIER ESTADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_037', 'CHECKS_FILECONTROL_PROCESOPENDIENTE', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A PENDIENTE GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_038', 'CHECKS_FILECONTROL_PROCESOTRASLADADO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A TRASLADADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_039', 'CHECKS_FILECONTROL_PROCESORECIBIDO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A RECIBIDO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_040', 'CHECKS_FILECONTROL_PROCESOARCHIVADO', 'PERMITE CAMBIAR ESTADO DEL PROCESO DEL CHEQUE A ARCHIVADO GESTIÓN DE CONTROL DE ARCHIVO DE CHEQUES EN EL SISTEMA.', 'CHECKS', 'UPDATE'),

('CHK_041', 'CHECKS_MANAGMENT_PRINT', 'PERMITE QUE EL USUARIO PUEDA IMPRIMIR EL REPORTE CONSULTADO.', 'CHECKS', 'PRINT'),

-- ==================================================== BANKS ============================================================================
('BNK_001', 'BANKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA BANKS EN EL SISTEMA.', 'BANKS', 'TAB'),

-- BANKS MENU ACCOUNTS
('BNK_002', 'BANKS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_003', 'BANKS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_004', 'BANKS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_005', 'BANKS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_006', 'BANKS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_007', 'BANKS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_008', 'BANKS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE BANCOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU MOVEMENTS
('BNK_009', 'BANKS_MOVEMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_010', 'BANKS_MOVEMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_011', 'BANKS_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_012', 'BANKS_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_013', 'BANKS_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_014', 'BANKS_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_015', 'BANKS_MOVEMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE MOVIMIENTOS BANCARIOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CONCILIATION
('BNK_016', 'BANKS_CONCILIATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_017', 'BANKS_CONCILIATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_018', 'BANKS_CONCILIATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_019', 'BANKS_CONCILIATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_020', 'BANKS_CONCILIATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_021', 'BANKS_CONCILIATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_022', 'BANKS_CONCILIATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONCILIACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CASHCONTROL
('BNK_023', 'BANKS_CASHCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_024', 'BANKS_CASHCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_025', 'BANKS_CASHCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_026', 'BANKS_CASHCONTROL_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_027', 'BANKS_CASHCONTROL_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_028', 'BANKS_CASHCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_029', 'BANKS_CASHCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL DE EFECTIVO EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU REPORTS
('BNK_030', 'BANKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_031', 'BANKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_032', 'BANKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_033', 'BANKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_034', 'BANKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_035', 'BANKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_036', 'BANKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES BANCARIOS EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- BANKS MENU CONFIGURATION
('BNK_037', 'BANKS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'TAB'),

('BNK_038', 'BANKS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'CREATE'),

('BNK_039', 'BANKS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'READ'),

('BNK_040', 'BANKS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'UPDATE'),

('BNK_041', 'BANKS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'INACTIVE'),

('BNK_042', 'BANKS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'EXPORT'),

('BNK_043', 'BANKS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN BANCARIA EN EL SISTEMA.', 'BANKS', 'IMPORT'),

-- ==================================================== ACCOUNTING BOOKS ============================================================================
('ACB_001', 'ACCOUNTINGBOOKS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA ACCOUNTINGBOOKS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

-- ACCOUNTING BOOKS MENU DAILYBOOK
('ACB_002', 'ACCOUNTINGBOOKS_DAILYBOOK', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_003', 'ACCOUNTINGBOOKS_DAILYBOOK_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_004', 'ACCOUNTINGBOOKS_DAILYBOOK_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_005', 'ACCOUNTINGBOOKS_DAILYBOOK_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_006', 'ACCOUNTINGBOOKS_DAILYBOOK_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_007', 'ACCOUNTINGBOOKS_DAILYBOOK_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_008', 'ACCOUNTINGBOOKS_DAILYBOOK_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LIBRO DIARIO EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU LEDGER (LIBRO MAYOR)
('ACB_009', 'ACCOUNTINGBOOKS_LEDGER', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_010', 'ACCOUNTINGBOOKS_LEDGER_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_011', 'ACCOUNTINGBOOKS_LEDGER_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_012', 'ACCOUNTINGBOOKS_LEDGER_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_013', 'ACCOUNTINGBOOKS_LEDGER_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_014', 'ACCOUNTINGBOOKS_LEDGER_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_015', 'ACCOUNTINGBOOKS_LEDGER_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LIBRO MAYOR EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU FINANCIAL STATEMANTS
('ACB_016', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_017', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_018', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_019', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_020', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_021', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_022', 'ACCOUNTINGBOOKS_FINANTIALSTATEMANTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE ESTADOS FINANCIEROS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU CLOSING
('ACB_023', 'ACCOUNTINGBOOKS_CLOSING', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_024', 'ACCOUNTINGBOOKS_CLOSING_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_025', 'ACCOUNTINGBOOKS_CLOSING_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_026', 'ACCOUNTINGBOOKS_CLOSING_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_027', 'ACCOUNTINGBOOKS_CLOSING_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_028', 'ACCOUNTINGBOOKS_CLOSING_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_029', 'ACCOUNTINGBOOKS_CLOSING_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CIERRE CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU REPORTS
('ACB_030', 'ACCOUNTINGBOOKS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_031', 'ACCOUNTINGBOOKS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_032', 'ACCOUNTINGBOOKS_REPORTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_033', 'ACCOUNTINGBOOKS_REPORTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_034', 'ACCOUNTINGBOOKS_REPORTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_035', 'ACCOUNTINGBOOKS_REPORTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_036', 'ACCOUNTINGBOOKS_REPORTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTERÍA CONTABLE EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),

-- ACCOUNTING BOOKS MENU CATALOG
('ACB_037', 'ACCOUNTINGBOOKS_CATALOG', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'TAB'),

('ACB_038', 'ACCOUNTINGBOOKS_CATALOG_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'CREATE'),

('ACB_039', 'ACCOUNTINGBOOKS_CATALOG_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'READ'),

('ACB_040', 'ACCOUNTINGBOOKS_CATALOG_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'UPDATE'),

('ACB_041', 'ACCOUNTINGBOOKS_CATALOG_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'INACTIVE'),

('ACB_042', 'ACCOUNTINGBOOKS_CATALOG_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'EXPORT'),

('ACB_043', 'ACCOUNTINGBOOKS_CATALOG_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CATÁLOGO DE CUENTAS EN EL SISTEMA.', 'ACCOUNTINGBOOKS', 'IMPORT'),
-- ==================================================== FINANCES ============================================================================
('FNS_001', 'FINANCES_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA FINANZAS EN EL SISTEMA.', 'FINANCES', 'TAB'),

-- ==================================================== TRANSFERS ============================================================================
('TNS_001', 'TRANSFERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

-- TRANSFERS MENU TRANSFERS_MANAGMENT
('TNS_002', 'TRANSFERS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

('TNS_003', 'TRANSFERS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'CREATE'),

('TNS_004', 'TRANSFERS_MANAGMENT__READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'READ'),

('TNS_005', 'TRANSFERS_MANAGMENT__UPDATE', 'PERMITE MODIFICAR GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'UPDATE'),

('TNS_006', 'TRANSFERS_MANAGMENT__INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'INACTIVE'),

('TNS_007', 'TRANSFERS_MANAGMENT__EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'EXPORT'),

('TNS_008', 'TRANSFERS_MANAGMENT__IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'IMPORT'),

-- TRANSFERS MENU TRANSFERS_MANAGMENT
('TNS_009', 'TRANSFERS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'TAB'),

('TNS_010', 'TRANSFERS_REPORTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'CREATE'),

('TNS_011', 'TRANSFERS_REPORTS__READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'READ'),

('TNS_012', 'TRANSFERS_REPORTS__UPDATE', 'PERMITE MODIFICAR GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'UPDATE'),

('TNS_013', 'TRANSFERS_REPORTS__INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE REPORTES TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'INACTIVE'),

('TNS_014', 'TRANSFERS_REPORTS__EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTES DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'EXPORT'),

('TNS_015', 'TRANSFERS_REPORTS__IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE REPORTES DE TRANSFERENCIAS EN EL SISTEMA.', 'TRANSFERS', 'IMPORT'),

('TNS_016', 'TRANSFERS_MANAGMENT_DELETE', 'PERMITE ELIMINAR UN REGISTRO DEL SISTEMA DE DE TRANSFERENCIAS.', 'TRANSFERS', 'DELETE')
) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)