INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 

-- ==================================================== LOCATIONS ============================================================================
('LOC_001', 'LOCATIONS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA LOCATIONS EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

-- LOCATIONS MENU MANAGMENT
('LOC_002', 'LOCATIONS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_003', 'LOCATIONS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_004', 'LOCATIONS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_005', 'LOCATIONS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_006', 'LOCATIONS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_007', 'LOCATIONS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_008', 'LOCATIONS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU CONFIGURATION
('LOC_009', 'LOCATIONS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_010', 'LOCATIONS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_011', 'LOCATIONS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_012', 'LOCATIONS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_013', 'LOCATIONS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_014', 'LOCATIONS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_015', 'LOCATIONS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU FINANTIAL CONTROL
('LOC_016', 'LOCATIONS_FINANTIALCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_017', 'LOCATIONS_FINANTIALCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_018', 'LOCATIONS_FINANTIALCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_019', 'LOCATIONS_FINANTIALCONTROL_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_020', 'LOCATIONS_FINANTIALCONTROL_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_021', 'LOCATIONS_FINANTIALCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_022', 'LOCATIONS_FINANTIALCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU DEPARTMENTS
('LOC_023', 'LOCATIONS_DEPARTMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_024', 'LOCATIONS_DEPARTMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_025', 'LOCATIONS_DEPARTMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_026', 'LOCATIONS_DEPARTMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_027', 'LOCATIONS_DEPARTMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_028', 'LOCATIONS_DEPARTMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_029', 'LOCATIONS_DEPARTMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU STAFF
('LOC_030', 'LOCATIONS_STAFF', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_031', 'LOCATIONS_STAFF_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_032', 'LOCATIONS_STAFF_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_033', 'LOCATIONS_STAFF_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_034', 'LOCATIONS_STAFF_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_035', 'LOCATIONS_STAFF_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_036', 'LOCATIONS_STAFF_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'IMPORT')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)