----------------IMPORTANTE------------------
----- ANTES DE ELIMINAR EL CHEQUE Y LAS PARTIDAS CONTABLES MAE, Y DETALLE
----- ES NECESARIO EN EL SISTEMA (INTERFAZ GRÁFICA) CAMBIAR EL ESTADO DEL CHEQUE
----- A ANULADO, DE FORMA QUE SE REVIERTEN LOS SALDOS AFECTADOS A LAS CUENTAS CONTABLES.

----- PASO 1 VISUALIZAMOS LISTADO DE CHEQUES --------
SELECT * FROM Checks;

----- PASO 2 VERIFICAR EL NÚMERO DE CHEQUE A ELIMINAR --------
SELECT * FROM Checks WHERE CheckNumber = '40219';

----- PASO 3 OBTENER EL CheckId en base al No. de Cheque, Siempre preferentemente corroborar 
----- que los datos del cheque corresponden a la solicitud que hacen --------

----- CheckId = 6094

----- PASO 4 VERIFICAR LA PARTIDA CONTABLE CHEQUES VINCULADA AL NO. DE CHEQUE --------
SELECT * FROM AccountingEntryChecks WHERE CheckId = 6094;

----- PASO 5 ANOTACIÓN DE LOS EntryMasterId PARA PODER BUSCAR EN TABLA DETALLE

----- EntryMasterId = 6160
----- EntryMasterId = 6184

----- PASO 6 BUSQUEDA EN TABLA DE DETALLE DE LA PARTIDA CONTABLE DE CHEQUES
SELECT * FROM AccountingEntryDetails 
WHERE 
EntryMasterId = 6160 
OR 
EntryMasterId = 6184;

----- PASO 7 ELIMINACIÓN DE REGISTROS EN TABLA DETALLE DE PARTIDA CHEQUE QUE ENCONTRAMOS
DELETE FROM AccountingEntryDetails 
WHERE 
EntryMasterId = 6160 
OR 
EntryMasterId = 6184;

----- PASO 8 ELIMINACIÓN DE REGISTRO EN LA TABLA PARTIDA DE CHEQUES
DELETE FROM AccountingEntryChecks WHERE CheckId = 6094;

----- PASO 9 ELIMINACIÓN DE REGISTRO EN LA TABLA PARTIDA MAESTRA

DELETE FROM AccountingEntryMaster 
WHERE 
EntryMasterId = 6160 
OR 
EntryMasterId = 6184;

----- PASO 10 ELIMINACIÓN DEL CHEQUE EN PARTIDA DE CHEQUES

DELETE FROM Checks WHERE CheckId = 6094;

----- PASO 11 VERIFICAMOS QUE NO QUEDARÁ REGISTRO DE CHEQUE, PARTIDA CHEQUE, PARTIDAS DETALLES, Y PARTIDA MAESTRA
SELECT * FROM Checks WHERE CheckId = 6094;
SELECT * FROM AccountingEntryChecks WHERE CheckId = 6094;
SELECT * FROM AccountingEntryDetails WHERE EntryMasterId = 6160 OR EntryMasterId = 6184;
SELECT * FROM AccountingEntryMaster WHERE EntryMasterId = 6160 OR EntryMasterId = 6184;