-- ==================================================== FIXED ASSETS ============================================================================

--FIXEDASSETS MODULO DE ACTIVOS FIJOS

INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES

('FA_001', 'FA_CATEGORIES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ.', 'FIXEDASSETS', 'TAB'),

('FA_002', 'FA_CATEGORIES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_003', 'FA_CATEGORIES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_004', 'FA_CATEGORIES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_005', 'FA_CATEGORIES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_006', 'FA_CATEGORIES_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_007', 'FA_ATTRIBUTES_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'CREATE'),

('FA_008', 'FA_ATTRIBUTES_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_009', 'FA_ATTRIBUTES_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_010', 'FA_ASSETS_CREATE', 'PERMITE REGISTRAR NUEVA REPORTERÍA EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_011', 'FA_ASSETS_UPDATE', 'PERMITE MODIFICAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_012', 'FA_ASSETS_INACTIVE', 'PERMITE DESACTIVAR REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_013', 'FA_ASSETS_EXPORT', 'PERMITE EXPORTAR LISTADO DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_014', 'FA_ASSETS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE REPORTERÍA EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_015', 'FA_MOVEMENTS_CREATE', 'PERMITE REGISTRAR TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_016', 'FA_MOVEMENTS_UPDATE', 'PERMITE MODIFICAR TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_017', 'FA_MOVEMENTS_INACTIVE', 'PERMITE DESACTIVAR TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_018', 'FA_MOVEMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_019', 'FA_MOVEMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_020', 'FA_MOVEMENTSSTATES_CREATE', 'PERMITE REGISTRAR ESTADOS DE TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_021', 'FA_MOVEMENTSSTATES_UPDATE', 'PERMITE MODIFICAR ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_022', 'FA_MOVEMENTSSTATES_INACTIVE', 'PERMITE DESACTIVAR ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_023', 'FA_MOVEMENTSSTATES_EXPORT', 'PERMITE EXPORTAR LISTADO DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_024', 'FA_MOVEMENTSSTATES_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE ESTADOS TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ'),

('FA_025', 'FA_MOVEMENTSTRANSITION_CREATE', 'PERMITE REGISTRAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA', 'FIXEDASSETS', 'CREATE'),

('FA_026', 'FA_MOVEMENTSTRANSITION_UPDATE', 'PERMITE MODIFICAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'UPDATE'),

('FA_027', 'FA_MOVEMENTSTRANSITION_INACTIVE', 'PERMITE DESACTIVAR TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'INACTIVE'),

('FA_028', 'FA_MOVEMENTSTRANSITION_EXPORT', 'PERMITE EXPORTAR LISTADO DE TRANSICIONES DE ESTADOS DE TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'EXPORT'),

('FA_029', 'FA_MOVEMENTSTRANSITION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE TRANSICIONES DE ESTADOS TRASLADOS EN EL SISTEMA.', 'FIXEDASSETS', 'READ')

)AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode);

