INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES 
-- ==================================================== EMPLOYEES ============================================================================

-- EMPLEADOS MENU PRINCIPAL
('EMP_001', 'EMPLOYEES_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA GESTIÓN DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

-- EMPLEADOS MODULO GESTIÓN DE EMPLEADOS
('EMP_002', 'EMPLOYEES_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_003', 'EMPLOYEES_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_004', 'EMPLOYEES_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE LOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_005', 'EMPLOYEES_MANAGMENT_UPDATE', 'PERMITE MODIFICAR INFORMACIÓN DE LOS EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_006', 'EMPLOYEES_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_007', 'EMPLOYEES_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_008', 'EMPLOYEES_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE EMPLEADOS EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO INFORMACIÓN LABORAL
('EMP_009', 'EMPLOYEES_INFORMATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_010', 'EMPLOYEES_INFORMATION_CREATE', 'PERMITE REGISTRAR NUEVA INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_011', 'EMPLOYEES_INFORMATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_012', 'EMPLOYEES_INFORMATION_UPDATE', 'PERMITE MODIFICAR INFORMACIÓN DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_013', 'EMPLOYEES_INFORMATION_INACTIVE', 'PERMITE DESACTIVAR INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_014', 'EMPLOYEES_INFORMATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_015', 'EMPLOYEES_INFORMATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE INFORMACIÓN LABORAL EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO CONFIGURACIÓN SALARIAL
('EMP_016', 'EMPLOYEES_SALARY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_017', 'EMPLOYEES_SALARY_CREATE', 'PERMITE REGISTRAR NUEVA CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_018', 'EMPLOYEES_SALARY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_019', 'EMPLOYEES_SALARY_UPDATE', 'PERMITE MODIFICAR CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_020', 'EMPLOYEES_SALARY_INACTIVE', 'PERMITE DESACTIVAR CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_021', 'EMPLOYEES_SALARY_EXPORT', 'PERMITE EXPORTAR LISTADO DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_022', 'EMPLOYEES_SALARY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CONFIGURACIÓN SALARIAL EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO NOMINA
('EMP_023', 'EMPLOYEES_NOMINA', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_024', 'EMPLOYEES_NOMINA_CREATE', 'PERMITE REGISTRAR NUEVA NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_025', 'EMPLOYEES_NOMINA_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_026', 'EMPLOYEES_NOMINA_UPDATE', 'PERMITE MODIFICAR NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_027', 'EMPLOYEES_NOMINA_INACTIVE', 'PERMITE DESACTIVAR NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_028', 'EMPLOYEES_NOMINA_EXPORT', 'PERMITE EXPORTAR LISTADO DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_029', 'EMPLOYEES_NOMINA_IMPORT', 'PERMITE IMPORTAR LISTADOS DE NOMINA EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO DEPARTMENTS
('EMP_030', 'EMPLOYEES_DEPARTMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_031', 'EMPLOYEES_DEPARTMENTS_CREATE', 'PERMITE REGISTRAR NUEVA DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_032', 'EMPLOYEES_DEPARTMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_033', 'EMPLOYEES_DEPARTMENTS_UPDATE', 'PERMITE MODIFICAR DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_034', 'EMPLOYEES_DEPARTMENTS_INACTIVE', 'PERMITE DESACTIVAR DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_035', 'EMPLOYEES_DEPARTMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_036', 'EMPLOYEES_DEPARTMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE DEPARTAMENTOS EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO TEACHERS
('EMP_037', 'EMPLOYEES_TEACHERS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_038', 'EMPLOYEES_TEACHERS_CREATE', 'PERMITE REGISTRAR NUEVA DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_039', 'EMPLOYEES_TEACHERS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_040', 'EMPLOYEES_TEACHERS_UPDATE', 'PERMITE MODIFICAR DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_041', 'EMPLOYEES_TEACHERS_INACTIVE', 'PERMITE DESACTIVAR DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_042', 'EMPLOYEES_TEACHERS_EXPORT', 'PERMITE EXPORTAR LISTADO DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_043', 'EMPLOYEES_TEACHERS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE DOCENTES EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO HISTORIAL Y AUDITORÍA
('EMP_044', 'EMPLOYEES_HISTORY', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_045', 'EMPLOYEES_HISTORY_CREATE', 'PERMITE REGISTRAR NUEVA HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_046', 'EMPLOYEES_HISTORY_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_047', 'EMPLOYEES_HISTORY_UPDATE', 'PERMITE MODIFICAR HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_048', 'EMPLOYEES_HISTORY_INACTIVE', 'PERMITE DESACTIVAR HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_049', 'EMPLOYEES_HISTORY_EXPORT', 'PERMITE EXPORTAR LISTADO DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_050', 'EMPLOYEES_HISTORY_IMPORT', 'PERMITE IMPORTAR LISTADOS DE HISTORIAL Y AUDITORÍA EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO CALENDARIO DE TRABAJO
('EMP_051', 'EMPLOYEES_CALENDAR', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_052', 'EMPLOYEES_CALENDAR_CREATE', 'PERMITE REGISTRAR NUEVA CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_053', 'EMPLOYEES_CALENDAR_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_054', 'EMPLOYEES_CALENDAR_UPDATE', 'PERMITE MODIFICAR CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_055', 'EMPLOYEES_CALENDAR_INACTIVE', 'PERMITE DESACTIVAR CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_056', 'EMPLOYEES_CALENDAR_EXPORT', 'PERMITE EXPORTAR LISTADO DE CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_057', 'EMPLOYEES_CALENDAR_IMPORT', 'PERMITE IMPORTAR LISTADOS DE CALENDARIO DE TRABAJO EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- EMPLEADOS MODULO PLANILLAS
('EMP_058', 'EMPLOYEES_SPREADSHEETS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'TAB'),

('EMP_059', 'EMPLOYEES_SPREADSHEETS_CREATE', 'PERMITE REGISTRAR NUEVA PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'CREATE'),

('EMP_060', 'EMPLOYEES_SPREADSHEETS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'READ'),

('EMP_061', 'EMPLOYEES_SPREADSHEETS_UPDATE', 'PERMITE MODIFICAR PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'UPDATE'),

('EMP_062', 'EMPLOYEES_SPREADSHEETS_INACTIVE', 'PERMITE DESACTIVAR PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'INACTIVE'),

('EMP_063', 'EMPLOYEES_SPREADSHEETS_EXPORT', 'PERMITE EXPORTAR LISTADO DE PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'EXPORT'),

('EMP_064', 'EMPLOYEES_SPREADSHEETS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE PLANILLAS EN EL SISTEMA.', 'EMPLOYEES', 'IMPORT'),

-- ==================================================== LOCATIONS ============================================================================
('LOC_001', 'LOCATIONS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA LOCATIONS EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

-- LOCATIONS MENU MANAGMENT
('LOC_002', 'LOCATIONS_MANAGMENT', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_003', 'LOCATIONS_MANAGMENT_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_004', 'LOCATIONS_MANAGMENT_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_005', 'LOCATIONS_MANAGMENT_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_006', 'LOCATIONS_MANAGMENT_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_007', 'LOCATIONS_MANAGMENT_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_008', 'LOCATIONS_MANAGMENT_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU CONFIGURATION
('LOC_009', 'LOCATIONS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_010', 'LOCATIONS_CONFIGURATION_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_011', 'LOCATIONS_CONFIGURATION_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_012', 'LOCATIONS_CONFIGURATION_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_013', 'LOCATIONS_CONFIGURATION_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_014', 'LOCATIONS_CONFIGURATION_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_015', 'LOCATIONS_CONFIGURATION_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONFIGURACIÓN DE LOCACIONES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU FINANTIAL CONTROL
('LOC_016', 'LOCATIONS_FINANTIALCONTROL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_017', 'LOCATIONS_FINANTIALCONTROL_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_018', 'LOCATIONS_FINANTIALCONTROL_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_019', 'LOCATIONS_FINANTIALCONTROL_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_020', 'LOCATIONS_FINANTIALCONTROL_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_021', 'LOCATIONS_FINANTIALCONTROL_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_022', 'LOCATIONS_FINANTIALCONTROL_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE CONTROL FINANCIERO POR SEDES EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU DEPARTMENTS
('LOC_023', 'LOCATIONS_DEPARTMENTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_024', 'LOCATIONS_DEPARTMENTS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_025', 'LOCATIONS_DEPARTMENTS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_026', 'LOCATIONS_DEPARTMENTS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_027', 'LOCATIONS_DEPARTMENTS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_028', 'LOCATIONS_DEPARTMENTS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_029', 'LOCATIONS_DEPARTMENTS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE DEPARTAMENTOS POR LOCACIÓN EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- LOCATIONS MENU STAFF
('LOC_030', 'LOCATIONS_STAFF', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('LOC_031', 'LOCATIONS_STAFF_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('LOC_032', 'LOCATIONS_STAFF_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('LOC_033', 'LOCATIONS_STAFF_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('LOC_034', 'LOCATIONS_STAFF_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('LOC_035', 'LOCATIONS_STAFF_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('LOC_036', 'LOCATIONS_STAFF_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE PERSONAL POR SEDE EN EL SISTEMA.', 'LOCATIONS', 'IMPORT'),

-- ==================================================== TEACHERS ============================================================================
('TCH_001', 'TEACHERS_TAB', 'PERMITE VISUALIZAR EL BOTÓN PRINCIPAL EN EL MENÚ PARA DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

-- TEACHERS MENU TEACHERS_PERSONAL
('TCH_002', 'TEACHERS_CONFIGURATION', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA CONFIGURACIÓN ACADÉMICA EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_003', 'TEACHERS_PERSONAL', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE DOCENTES, COORDINADORES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_004', 'TEACHERS_SECTIONS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE SECCIONES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_005', 'TEACHERS_SCHEDULES', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE HORARIOS EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_006', 'TEACHERS_REPORTS', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE REPORTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_007', 'TEACHERS_PERSONAL_TEACHERMANAGMENT', 'PERMITE REGISTRAR NUEVA GESTIÓN DE DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_008', 'TEACHERS_PERSONAL_COORDINATORMANAGMENT', 'PERMITE REGISTRAR NUEVA GESTIÓN DE COORDINADORES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

('TCH_009', 'TEACHERS_PERSONAL_ASSIGNMENTCOURSES', 'PERMITE REGISTRAR ASIGNACIÓN DE CURSOS DE DOCENTES EN EL SISTEMA.', 'TEACHERS', 'TAB'),

-- DOCENCIA MENU COORDINATORS
('EMP_065', 'EMPLOYEES_COORDINATORS_FILE', 'PERMITE VISUALIZAR EL BOTÓN EN SUBMENÚ PARA GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'TAB'),

('EMP_066', 'EMPLOYEES_COORDINATORS_CREATE', 'PERMITE REGISTRAR NUEVA GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'CREATE'),

('EMP_067', 'EMPLOYEES_COORDINATORS_READ', 'PERMITE VISUALIZAR LA LISTA Y DETALLES DE GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'READ'),

('EMP_068', 'EMPLOYEES_COORDINATORS_UPDATE', 'PERMITE MODIFICAR GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'UPDATE'),

('EMP_069', 'EMPLOYEES_COORDINATORS_INACTIVE', 'PERMITE DESACTIVAR GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'INACTIVE'),

('EMP_070', 'EMPLOYEES_COORDINATORS_EXPORT', 'PERMITE EXPORTAR LISTADO DE GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'EXPORT'),

('EMP_071', 'EMPLOYEES_COORDINATORS_IMPORT', 'PERMITE IMPORTAR LISTADOS DE GESTIÓN DE FICHA DE COORDINADOR EN EL SISTEMA.', 'LOCATIONS', 'IMPORT')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode)