-- ============================================================
-- PERMISOS - ITSM TECHNOLOGY
-- ============================================================
INSERT INTO Permissions (PermissionCode, PermissionName, Description, ModuleName, ActionType)
SELECT * FROM (VALUES

('ITSM_001', 'USERS_ITSM_TECHONOLOGY',        'PERMITE VISUALIZAR EL MÓDULO DE GESTIÓN DE EQUIPOS DE TECNOLOGÍA.', 'ITSM', 'TAB'),
('ITSM_002', 'ITSM_TECHNOLOGY_READ',           'PERMITE VISUALIZAR LA LISTA Y DETALLES DE EQUIPOS DE TECNOLOGÍA.',  'ITSM', 'READ'),
('ITSM_003', 'ITSM_TECHNOLOGY_UPDATE',         'PERMITE MODIFICAR EQUIPOS DE TECNOLOGÍA.',                          'ITSM', 'UPDATE'),
('ITSM_004', 'ITSM_TECHNOLOGY_EXPORT',         'PERMITE EXPORTAR LISTADO DE EQUIPOS DE TECNOLOGÍA.',                'ITSM', 'EXPORT'),
('ITSM_005', 'ITSM_TECHNOLOGY_PRINT_LETTER',   'PERMITE EMITIR CARTA DE RESPONSABILIDAD DE EQUIPOS.',              'ITSM', 'EXPORT'),
('ITSM_006', 'ITSM_CLASSIFICATION_TAB',        'PERMITE VISUALIZAR EL MÓDULO DE CLASIFICACIONES DE CATEGORÍAS.',   'ITSM', 'TAB'),
('ITSM_007', 'ITSM_CLASSIFICATION_CREATE',     'PERMITE REGISTRAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'CREATE'),
('ITSM_008', 'ITSM_CLASSIFICATION_UPDATE',     'PERMITE MODIFICAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'UPDATE'),
('ITSM_009', 'ITSM_CLASSIFICATION_INACTIVE',   'PERMITE INACTIVAR CLASIFICACIONES DE CATEGORÍAS.',                  'ITSM', 'INACTIVE')

) AS nuevos(PermissionCode, PermissionName, Description, ModuleName, ActionType)
WHERE NOT EXISTS (
    SELECT 1 FROM Permissions p WHERE p.PermissionCode = nuevos.PermissionCode
);

SELECT * FROM Permissions