-- CATÁLOGOS ESTADOS DE SOLICITUDES DE COMPRAS
CREATE TABLE PurchaseRequestStatus (
    StatusId INT IDENTITY(1,1) PRIMARY KEY,
    StatusCode VARCHAR(20) NOT NULL UNIQUE,
    StatusName VARCHAR(50) NOT NULL,
    IsActive BIT DEFAULT 1
);
-- 'EN_REVISION', 'REVISADA', 'APROBADA', 'RECHAZADA', 'CORREGIR'