CREATE TABLE Brands (
    BrandId INT IDENTITY(1,1) PRIMARY KEY,
    BrandName VARCHAR(100) NOT NULL UNIQUE,
    Category VARCHAR(50),
    IsActive BIT DEFAULT 1
);
-- Insertar marcas sin duplicados (TODO EN MAYÚSCULAS)
INSERT INTO Brands (BrandName, Category) VALUES
-- COMPUTADORAS Y TECNOLOGÍA
('HP', 'COMPUTADORAS'),
('DELL', 'COMPUTADORAS'),
('APPLE', 'COMPUTADORAS'),
('LENOVO', 'COMPUTADORAS'),
('SAMSUNG', 'COMPUTADORAS'),
('SONY', 'COMPUTADORAS'),
('ACER', 'COMPUTADORAS'),
('ASUS', 'COMPUTADORAS'),
('MICROSOFT', 'COMPUTADORAS'),
('LG', 'COMPUTADORAS'),
('RAZER', 'COMPUTADORAS'),
('LOGITECH', 'COMPUTADORAS'),
('HUAWEI', 'COMPUTADORAS'),
('TOSHIBA', 'COMPUTADORAS'),

-- IMPRESORAS
('CANON', 'IMPRESORAS'),
('EPSON', 'IMPRESORAS'),
('BROTHER', 'IMPRESORAS'),
('XEROX', 'IMPRESORAS'),
('RICOH', 'IMPRESORAS'),
('KYOCERA', 'IMPRESORAS'),
('LEXMARK', 'IMPRESORAS'),
('OKI', 'IMPRESORAS'),

-- MÓVILES
('NOKIA', 'MÓVILES'),
('XIAOMI', 'MÓVILES'),
('MOTOROLA', 'MÓVILES'),
('ONEPLUS', 'MÓVILES'),
('GOOGLE', 'MÓVILES'),

-- TELEFONÍA
('AVAYA', 'TELEFONÍA'),
('CISCO', 'TELEFONÍA'),
('ALCATEL-LUCENT', 'TELEFONÍA'),
('PANASONIC', 'TELEFONÍA'),
('NEC', 'TELEFONÍA'),
('SIEMENS', 'TELEFONÍA'),
('MITEL', 'TELEFONÍA'),
('3CX', 'TELEFONÍA'),
('ASTERISK', 'TELEFONÍA'),
('GRANDSTREAM', 'TELEFONÍA'),

-- OTROS
('VIZIO', 'OTROS'),
('BENQ', 'OTROS'),
('VIEWSONIC', 'OTROS'),
('JVC', 'OTROS'),
('SHARP', 'OTROS'),
('PHILIPS', 'OTROS'),
('OTRAS', 'OTROS');