-- =============================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- =============================================

-- Índices para Employees
CREATE NONCLUSTERED INDEX IX_Employees_Code ON Employees(EmployeeCode);
CREATE NONCLUSTERED INDEX IX_Employees_InstitutionalEmail ON Employees(InstitutionalEmail);
CREATE NONCLUSTERED INDEX IX_Employees_Department ON Employees(DepartmentId);
CREATE NONCLUSTERED INDEX IX_Employees_Position ON Employees(PositionId);
CREATE NONCLUSTERED INDEX IX_Employees_Status ON Employees(EmployeeStatusId);
CREATE NONCLUSTERED INDEX IX_Employees_Supervisor ON Employees(DirectSupervisorId);

-- Índices para Users
CREATE NONCLUSTERED INDEX IX_Users_Username ON Users(Username);
CREATE NONCLUSTERED INDEX IX_Users_InstitutionalEmail ON Users(InstitutionalEmail);
CREATE NONCLUSTERED INDEX IX_Users_Status ON Users(StatusId);
CREATE NONCLUSTERED INDEX IX_Users_Role ON Users(RoleId);
CREATE NONCLUSTERED INDEX IX_Users_Employee ON Users(EmployeeId);

-- Índices para Permissions
CREATE NONCLUSTERED INDEX IX_Permissions_Code ON Permissions(PermissionCode);
CREATE NONCLUSTERED INDEX IX_Permissions_Module ON Permissions(ModuleName);
CREATE NONCLUSTERED INDEX IX_RolePermissions_Role ON RolePermissions(RoleId);
CREATE NONCLUSTERED INDEX IX_UserPermissions_User ON UserPermissions(UserId);

-- Índices para Auditoría
CREATE NONCLUSTERED INDEX IX_AuditLog_User ON AuditLog(UserId);
CREATE NONCLUSTERED INDEX IX_AuditLog_Date ON AuditLog(ActionDate);
CREATE NONCLUSTERED INDEX IX_AuditLog_Table ON AuditLog(TableName);

-- =============================================
-- DATOS INICIALES BÁSICOS
-- =============================================

-- Estados de Empleados
INSERT INTO EmployeeStatus (StatusName, Description) VALUES 
('ACTIVO', 'EMPLEADO ACTIVO'),
('INACTIVO', 'EMPLEADO INACTIVO'),
('SUSPENDIDO', 'EMPLEADO SUSPENDIDO'),
('TEMPORAL', 'EMPLEADO TEMPORAL');

-- Estados de Usuarios
INSERT INTO UserStatus (StatusName, Description) VALUES
('ACTIVO', 'USUARIO ACTIVO'),
('INACTIVO', 'USUARIO INACTIVO'),
('SUSPENDIDO', 'USUARIO SUSPENDIDO');

-- ROLES BÁSICOS
INSERT INTO Roles (RoleName, Description) VALUES 
('SUPERADMIN', 'ADMINISTRADOR DEL SISTEMA CON ACCESO TOTAL'),
('ADMIN', 'ADMINISTRADOR CON PERMISOS LIMITADOS'),
('AUXILIAR DE CONTABILIDAD', 'GESTIONA REGISTROS CONTABLES, REALIZA CONCILIACIONES Y SOPORTA AL CONTADOR EN TAREAS ADMINISTRATIVAS.'),
('CONTADOR', 'REVISA Y ANALIZA LA INFORMACIÓN CONTABLE Y FINANCIERA; TIENE PERMISOS PRINCIPALMENTE DE LECTURA Y VALIDACIÓN.'),
('ASISTENTE', 'APOYA EN TAREAS ADMINISTRATIVAS Y OPERATIVAS, PUEDE INGRESAR INFORMACIÓN Y GENERAR REPORTES BÁSICOS.'),
('AUDITOR', 'REVISA Y CONTROLA LA INTEGRIDAD DE LA INFORMACIÓN CONTABLE Y ADMINISTRATIVA; ACCESO PRINCIPALMENTE PARA CONSULTAS Y REPORTES DE AUDITORÍA.'),
('ALMACENISTA', 'GESTIONA INVENTARIOS, REALIZA REGISTROS DE ENTRADAS Y SALIDAS DE PRODUCTOS, Y MANTIENE ACTUALIZADO EL KARDEX.'),
('IT', 'ADMINISTRA LA INFRAESTRUCTURA TECNOLÓGICA, MANTIENE EL SISTEMA OPERATIVO Y DE BASE DE DATOS, Y GESTIONA PERMISOS Y SEGURIDAD DEL SISTEMA.'),
('ENCARGADO DE COMPRAS', 'ENCARGADO DE CREAR SOLICITUDES, ÓRDENES DE COMPRA Y SEGUIMIENTO DE PROVEEDORES.'),
('ANALISTA DE RECURSOS HUMANOS', 'ENCARGADO DE ANALIZAR Y GESTIONAR PROCESOS CON RELACIÓN AL TALENTO HUMANO Y BIENESTAR DE LOS COLABORADORES Y LA INSTITUCIÓN');

-- LOCATIONS (Sedes)
INSERT INTO Locations (LocationCode, LocationName) VALUES
-- Inserción de sedes en Locations
('1', 'CENTRAL'),
('25', 'BOCA DEL MONTE'),
('26', 'CALZADA SAN JUAN'),
('50', 'MIXCO'),
('55', 'SANTA CATARINA PINULA'),
('27', 'SAN CRISTOBAL'),
('49', 'SAN RAYMUNDO'),
('2', 'VILLA CANALES'),
('19', 'ESCUINTLA'),
('45', 'MASAGUA'),
('23', 'NUEVA CONCEPCION'),
('53', 'PALIN'),
('44', 'PUERTO SAN JOSÉ'),
('22', 'SANTA LUCIA'),
('79', 'SIPACATE'),
('20', 'BARBERENA'),
('52', 'NUEVA SANTA ROSA'),
('17', 'ORATORIO'),
('51', 'TAXISCO'),
('21', 'CHIQUIMULILLA'),
('56', 'CHICACAO'),
('16', 'MAZATENANGO'),
('57', 'PATULUL'),
('12', 'RETALHULEU'),
('11', 'COATEPEQUE'),
('24', 'SALCAJA'),
('54', 'SAN JUAN OSTUNCALCO'),
('80', 'QUETZALTENANGO');

-- Departamentos Básicos (Sede Central)
INSERT INTO Departments (LocationId, DepartmentCode, DepartmentName, Description) VALUES 
(1, '1-IT-01', 'INFORMATICA', 'DEPARTAMENTO DE TECNOLOGIA DE LA INFORMACION'),
(1, '1-AUD-01', 'AUDITORIA', 'DEPARTAMENTO DE AUDITORIA INTERNA'),
(1, '1-ADM-01', 'CONTABILIDAD', 'DEPARTAMENTO ADMINISTRATIVO Y CONTABLE'),
(1, '1-ACA-01', 'CONTROL ACADEMICO', 'DEPARTAMENTO ACADEMICO'),
(1, '1-FIN-01', 'COORDINACION', 'DEPARTAMENTO DE COORDINACIÓN'),
(1, '1-CC-01', 'CUENTA CORRIENTE', 'DEPARTAMENTO DE CUENTAS CORRIENTES'),
(1, '1-DIS-01', 'DISEÑO', 'DEPARTAMENTO DE DISEÑO GRAFICO Y COMUNICACION VISUAL'),
(1, '1-PRO-01', 'PROCESOS ACADEMICOS', 'DEPARTAMENTO DE PROCESOS ACADEMICOS'),
(1, '1-NL-01', 'NEOLINK', 'DEPARTAMENTO DE SISTEMAS NEOLINK'),
(1, '1-PUB-01', 'PUBLICIDAD', 'DEPARTAMENTO DE PUBLICIDAD Y MARKETING'),
(1, '1-RH-01', 'RECURSOS HUMANOS', 'DEPARTAMENTO DE GESTION DE PERSONAL Y TALENTO HUMANO'),
(1, '1-MAN-01', 'MANTENIMIENTO', 'DEPARTAMENTO DE MANTENIMIENTO DE INSTALACIONES'),
(1, '1-LOG-01', 'LOGISTICA', 'DEPARTAMENTO DE LOGISTICA Y TRANSPORTE INTERNO'),
(1, '1-SEG-01', 'SEGURIDAD', 'DEPARTAMENTO DE SEGURIDAD Y VIGILANCIA');

-- POR REVISAR
--*******************************
-- Permisos Básicos
INSERT INTO Permissions (PermissionCode, PermissionName, ModuleName, ActionType) VALUES 
('SEC_LOGIN', 'Iniciar Sesión', 'Security', 'Execute'),
('SEC_USER_CREATE', 'Crear Usuarios', 'Security', 'Create'),
('SEC_USER_READ', 'Ver Usuarios', 'Security', 'Read'),
('SEC_USER_UPDATE', 'Modificar Usuarios', 'Security', 'Update'),
('SEC_USER_DELETE', 'Eliminar Usuarios', 'Security', 'Delete'),
('SYS_CONFIG', 'Configurar Sistema', 'System', 'Update');

-- Categorías de Locations
INSERT INTO LocationCategories (CategoryCode, CategoryName, Description) VALUES
('PEQUEÑA', 'Sede Pequeña', 'Plantilla para sedes con inventario reducido'),
('MEDIANA', 'Sede Mediana', 'Plantilla para sedes con inventario moderado'),
('GRANDE', 'Sede Grande', 'Plantilla para sedes con inventario amplio');